// User attributes messages

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: protos/WebAPI/user_attribute_2.proto

package WebAPI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User defined attribute.
type UserAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Attribute name.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// Attribute value (optional for modification if attribute is deleted).
	Value *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	// True if attribute has to be deleted during modify operation.
	Deleted *bool `protobuf:"varint,3,opt,name=deleted" json:"deleted,omitempty"`
}

func (x *UserAttribute) Reset() {
	*x = UserAttribute{}
	mi := &file_protos_WebAPI_user_attribute_2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAttribute) ProtoMessage() {}

func (x *UserAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_protos_WebAPI_user_attribute_2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAttribute.ProtoReflect.Descriptor instead.
func (*UserAttribute) Descriptor() ([]byte, []int) {
	return file_protos_WebAPI_user_attribute_2_proto_rawDescGZIP(), []int{0}
}

func (x *UserAttribute) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserAttribute) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *UserAttribute) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

// Modification of order's user attributes.
type ModifyUserAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the order chain.
	ChainOrderId *string `protobuf:"bytes,1,req,name=chain_order_id,json=chainOrderId" json:"chain_order_id,omitempty"`
	// ID of the order's account.
	AccountId *int32 `protobuf:"zigzag32,2,req,name=account_id,json=accountId" json:"account_id,omitempty"`
	// List of attributes to modify.
	// See Order.user_attribute for additional description.
	UserAttributes []*UserAttribute `protobuf:"bytes,3,rep,name=user_attributes,json=userAttributes" json:"user_attributes,omitempty"`
	// Flag used by the client for marking the user attributes checked/unchecked.
	// Empty means to leave the flag the same as it was.
	IsChecked *bool `protobuf:"varint,4,opt,name=is_checked,json=isChecked" json:"is_checked,omitempty"`
}

func (x *ModifyUserAttributes) Reset() {
	*x = ModifyUserAttributes{}
	mi := &file_protos_WebAPI_user_attribute_2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserAttributes) ProtoMessage() {}

func (x *ModifyUserAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_WebAPI_user_attribute_2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserAttributes.ProtoReflect.Descriptor instead.
func (*ModifyUserAttributes) Descriptor() ([]byte, []int) {
	return file_protos_WebAPI_user_attribute_2_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyUserAttributes) GetChainOrderId() string {
	if x != nil && x.ChainOrderId != nil {
		return *x.ChainOrderId
	}
	return ""
}

func (x *ModifyUserAttributes) GetAccountId() int32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *ModifyUserAttributes) GetUserAttributes() []*UserAttribute {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *ModifyUserAttributes) GetIsChecked() bool {
	if x != nil && x.IsChecked != nil {
		return *x.IsChecked
	}
	return false
}

var File_protos_WebAPI_user_attribute_2_proto protoreflect.FileDescriptor

var file_protos_WebAPI_user_attribute_2_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x57, 0x65, 0x62, 0x41, 0x50, 0x49, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x32,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x32, 0x22, 0x53, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xc4, 0x01,
	0x0a, 0x14, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x11,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x48, 0x0a, 0x0f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x64, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x57, 0x65, 0x62, 0x41, 0x50, 0x49,
}

var (
	file_protos_WebAPI_user_attribute_2_proto_rawDescOnce sync.Once
	file_protos_WebAPI_user_attribute_2_proto_rawDescData = file_protos_WebAPI_user_attribute_2_proto_rawDesc
)

func file_protos_WebAPI_user_attribute_2_proto_rawDescGZIP() []byte {
	file_protos_WebAPI_user_attribute_2_proto_rawDescOnce.Do(func() {
		file_protos_WebAPI_user_attribute_2_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_WebAPI_user_attribute_2_proto_rawDescData)
	})
	return file_protos_WebAPI_user_attribute_2_proto_rawDescData
}

var file_protos_WebAPI_user_attribute_2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_WebAPI_user_attribute_2_proto_goTypes = []any{
	(*UserAttribute)(nil),        // 0: user_attribute_2.UserAttribute
	(*ModifyUserAttributes)(nil), // 1: user_attribute_2.ModifyUserAttributes
}
var file_protos_WebAPI_user_attribute_2_proto_depIdxs = []int32{
	0, // 0: user_attribute_2.ModifyUserAttributes.user_attributes:type_name -> user_attribute_2.UserAttribute
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_WebAPI_user_attribute_2_proto_init() }
func file_protos_WebAPI_user_attribute_2_proto_init() {
	if File_protos_WebAPI_user_attribute_2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_WebAPI_user_attribute_2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_WebAPI_user_attribute_2_proto_goTypes,
		DependencyIndexes: file_protos_WebAPI_user_attribute_2_proto_depIdxs,
		MessageInfos:      file_protos_WebAPI_user_attribute_2_proto_msgTypes,
	}.Build()
	File_protos_WebAPI_user_attribute_2_proto = out.File
	file_protos_WebAPI_user_attribute_2_proto_rawDesc = nil
	file_protos_WebAPI_user_attribute_2_proto_goTypes = nil
	file_protos_WebAPI_user_attribute_2_proto_depIdxs = nil
}
